export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const SERVICE_CHOOSE_REQUEST = "SERVICE_CHOOSE_REQUEST";
export const SERVICE_CHOOSE_FAILURE = "SERVICE_CHOOSE_FAILURE";
export const SERVICE_CHOOSE_SUCCESS = "SERVICE_CHOOSE_SUCCESS";
